#!/usr/bin/env python3.11
"""
Prepare the adjoint (backward) run for RTM inversion.

1. Compute residuals: r(t) = u_sim(t) - d_obs(t)
2. Time-reverse: s(t) = r(T - t)
3. Write misfit source files
4. Generate input_backward.spec

Usage:
    python3.11 scripts/prepare_adjoint.py
    python3.11 scripts/prepare_adjoint.py --outdir SEM3D_ST7_backward
"""

import h5py
import numpy as np
import os
import argparse
import sys

sys.path.insert(0, os.path.dirname(__file__))
from compare_traces import load_traces


def compute_residuals(uobs_time, uobs_disp, sim_time, sim_disp, stations):
    """Compute time-reversed residuals for adjoint sources.
    
    Adjoint source: s_r(t) = [u_sim(T-t) - d_obs(T-t)] for each station r
    Which is equivalent to: time_reverse(u_sim(t) - d_obs(t))
    """
    from scipy.interpolate import interp1d
    
    residuals = {}
    
    for station in stations:
        # Interpolate sim onto uobs time grid
        sim_interp = np.zeros_like(uobs_disp[station])
        for c in range(3):
            f = interp1d(sim_time, sim_disp[station][:, c], 
                        kind='linear', fill_value=0.0, bounds_error=False)
            sim_interp[:, c] = f(uobs_time)
        
        # Residual: sim - obs
        residual = sim_interp - uobs_disp[station]
        
        # Time-reverse
        residual_reversed = residual[::-1, :]
        
        residuals[station] = residual_reversed
    
    return residuals


def write_misfit_sources(uobs_time, residuals, stations, outdir):
    """Write misfit source time functions as text files."""
    src_dir = os.path.join(outdir, 'msf')
    os.makedirs(src_dir, exist_ok=True)
    
    T = uobs_time[-1]
    # Time vector for the adjoint run (forward in time, but sources are reversed)
    t_adj = uobs_time  # same time vector, residuals already reversed
    
    n_written = 0
    for station in stations:
        idx = station.split('_')[-1]  # e.g., '0000'
        for c, comp in enumerate(['x', 'y', 'z']):
            filename = f'm{idx}_{comp}.txt'
            filepath = os.path.join(src_dir, filename)
            data = np.column_stack([t_adj, residuals[station][:, c]])
            np.savetxt(filepath, data, fmt='%.15e %.15e')
            n_written += 1
    
    print(f"Written {n_written} misfit source files to {src_dir}/")
    return src_dir


def generate_backward_spec(uobs_time, stations, pos, src_dir, outdir, 
                           template_spec=None):
    """Generate input_backward.spec for the adjoint simulation."""
    
    # Read forward input.spec as template for common settings
    if template_spec is None:
        template_spec = os.path.join(outdir, 'input.spec')
    
    spec_path = os.path.join(outdir, 'input_backward.spec')
    
    with open(spec_path, 'w') as f:
        f.write('# -*- mode: perl -*-\n')
        f.write('# Adjoint (backward) simulation for RTM\n')
        f.write('# Auto-generated by prepare_adjoint.py\n\n')
        
        f.write('run_name = "RTM_Adjoint";\n\n')
        f.write('# Duration must match forward run\n')
        f.write(f'sim_time = {uobs_time[-1]:.4f};\n\n')
        
        f.write('mesh_file = "mesh4spec";\n')
        f.write('mat_file = "material.input";\n')
        f.write('dim = 3;\n')
        f.write('fmax = 0.1;\n')
        f.write('ngll = 5;\n\n')
        
        # Snapshots: save at ALL GLL points for gradient computation
        f.write('snapshots {\n')
        f.write('    save_snap = true;\n')
        f.write('    snap_interval = 0.1;\n')
        f.write('    select box = -1200.0 -1200.0 -1500.0 1200.0 1200.0 1.0;\n')
        f.write('};\n\n')
        
        f.write('mpml_atn_param = 0.02;\n\n')
        
        # No capteurs needed for adjoint (we use snapshots)
        f.write('save_traces = false;\n\n')
        
        f.write('# Fichier protection reprise\n')
        f.write('prorep = false;\n')
        f.write('prorep_iter = 200000;\n')
        f.write('restart_iter = 0;\n\n')
        
        # Write one source per station per component (121 × 3 = 363 sources)
        f.write(f'# Adjoint sources: {len(stations)} stations × 3 components = {len(stations)*3} sources\n')
        f.write('# Each source is a time-reversed residual at a receiver location\n\n')
        
        dir_vectors = {'x': '1 0 0', 'y': '0 1 0', 'z': '0 0 1'}
        
        for station in stations:
            idx = station.split('_')[-1]
            p = pos[station]
            
            for comp, dir_vec in dir_vectors.items():
                f.write(f'source {{\n')
                f.write(f'    coords = {p[0]:.5f} {p[1]:.5f} {p[2]:.5f};\n')
                f.write(f'    type = impulse;\n')
                f.write(f'    dir = {dir_vec};\n')
                f.write(f'    func = file;\n')
                f.write(f'    time_file = "msf/m{idx}_{comp}.txt";\n')
                f.write(f'    amplitude = 1.0;\n')
                f.write(f'}};\n\n')
        
        # Time scheme (same as forward)
        f.write('time_scheme {\n')
        f.write('    accel_scheme = false;\n')
        f.write('    veloc_scheme = true;\n')
        f.write('    alpha = 0.5;\n')
        f.write('    beta = 0.5;\n')
        f.write('    gamma = 1;\n')
        f.write('    courant = 0.2;\n')
        f.write('};\n\n')
        
        # PML (same as forward)
        f.write('pml_infos {\n')
        f.write('    pml_type = CPML;\n')
        f.write('    cpml_kappa0 = 10.0;\n')
        f.write('    cpml_kappa1 = 10.0;\n')
        f.write('    cpml_rc = 0.000000001;\n')
        f.write('    cpml_integration = Order2;\n')
        f.write('};\n\n')
        
        # Output: displacement + strain for gradient computation
        f.write('out_variables {\n')
        f.write('    enP  = 0;\n')
        f.write('    enS  = 0;\n')
        f.write('    evol = 1;  # volumetric strain\n')
        f.write('    pre  = 0;\n')
        f.write('    dis  = 1;  # displacement\n')
        f.write('    vel  = 0;\n')
        f.write('    acc  = 0;\n')
        f.write('    edev = 1;  # deviatoric strain\n')
        f.write('    sdev = 0;\n')
        f.write('};\n')
    
    print(f"Written: {spec_path}")
    print(f"  {len(stations) * 3} adjoint sources defined")


def plot_residuals(uobs_time, residuals, stations, output='residuals.png'):
    """Plot sample residuals to verify."""
    import matplotlib.pyplot as plt
    
    sample_stations = [stations[0], stations[len(stations)//2], stations[-1]]
    components = ['Ux', 'Uy', 'Uz']
    
    fig, axes = plt.subplots(len(sample_stations), 3, figsize=(16, 8), sharex=True)
    fig.suptitle('Time-Reversed Residuals (Adjoint Sources)', fontsize=14, fontweight='bold')
    
    for i, station in enumerate(sample_stations):
        for j, comp in enumerate(components):
            ax = axes[i, j]
            ax.plot(uobs_time, residuals[station][:, j], 'g-', linewidth=0.6)
            ax.set_xlim(0, uobs_time[-1])
            ax.grid(True, alpha=0.3)
            if i == 0:
                ax.set_title(comp)
            if j == 0:
                ax.set_ylabel(f'{station}\nResidual (m)', fontsize=9)
            if i == len(sample_stations) - 1:
                ax.set_xlabel('Time (s)')
    
    plt.tight_layout()
    plt.savefig(output, dpi=150, bbox_inches='tight')
    print(f"Saved: {output}")


def main():
    parser = argparse.ArgumentParser(description='Prepare adjoint run for RTM')
    parser.add_argument('--uobs', type=str, default='Uobs/capteurs.0025.h5')
    parser.add_argument('--sim', type=str, default='SEM3D_ST7/traces/')
    parser.add_argument('--outdir', type=str, default='SEM3D_ST7')
    args = parser.parse_args()

    # Load data
    print(f"\nLoading Uobs: {args.uobs}")
    uobs_time, uobs_disp, uobs_pos = load_traces(args.uobs)
    print(f"  {len(uobs_disp)} stations, {len(uobs_time)} time steps")
    
    print(f"Loading Sim: {args.sim}")
    sim_time, sim_disp, sim_pos = load_traces(args.sim)
    print(f"  {len(sim_disp)} stations, {len(sim_time)} time steps")
    
    stations = sorted(set(uobs_disp.keys()) & set(sim_disp.keys()))
    print(f"Matching stations: {len(stations)}")
    
    # Compute residuals
    print("\nComputing time-reversed residuals...")
    residuals = compute_residuals(uobs_time, uobs_disp, sim_time, sim_disp, stations)
    
    # Stats
    all_res = np.array([residuals[s] for s in stations])
    for i, c in enumerate(['Ux', 'Uy', 'Uz']):
        print(f"  {c}: max={np.abs(all_res[:,:,i]).max():.2e}, rms={np.sqrt(np.mean(all_res[:,:,i]**2)):.2e}")
    
    # Write misfit source files
    print()
    src_dir = write_misfit_sources(uobs_time, residuals, stations, args.outdir)
    
    # Generate backward input.spec
    generate_backward_spec(uobs_time, stations, uobs_pos, src_dir, args.outdir)
    
    plot_residuals(uobs_time, residuals, stations, output='residuals.png')


if __name__ == '__main__':
    main()
