# -*- mode: perl -*-
# Adjoint (backward) simulation for RTM
# Auto-generated by prepare_adjoint.py

run_name = "RTM_Adjoint";

# Duration must match forward run
sim_time = 1.9994;

mesh_file = "mesh4spec";
mat_file = "material.input";
dim = 3;
fmax = 0.1;
ngll = 5;

snapshots {
    save_snap = true;
    snap_interval = 0.1;
    select box = -1200.0 -1200.0 -1500.0 1200.0 1200.0 1.0;
};

mpml_atn_param = 0.02;

save_traces = false;

# Fichier protection reprise
prorep = false;
prorep_iter = 200000;
restart_iter = 0;

# Adjoint sources: 121 stations × 3 components = 363 sources
# Each source is a time-reversed residual at a receiver location

source {
    coords = -17.50000 -17.50000 0.00000;
    type = impulse;
    dir = 1 0 0;
    func = file;
    time_file = "msf/m0000_x.txt";
    amplitude = 1.0;
};

source {
    coords = -17.50000 -17.50000 0.00000;
    type = impulse;
    dir = 0 1 0;
    func = file;
    time_file = "msf/m0000_y.txt";
    amplitude = 1.0;
};

source {
    coords = -17.50000 -17.50000 0.00000;
    type = impulse;
    dir = 0 0 1;
    func = file;
    time_file = "msf/m0000_z.txt";
    amplitude = 1.0;
};

source {
    coords = -17.50000 -14.00000 0.00000;
    type = impulse;
    dir = 1 0 0;
    func = file;
    time_file = "msf/m0001_x.txt";
    amplitude = 1.0;
};

source {
    coords = -17.50000 -14.00000 0.00000;
    type = impulse;
    dir = 0 1 0;
    func = file;
    time_file = "msf/m0001_y.txt";
    amplitude = 1.0;
};

source {
    coords = -17.50000 -14.00000 0.00000;
    type = impulse;
    dir = 0 0 1;
    func = file;
    time_file = "msf/m0001_z.txt";
    amplitude = 1.0;
};

source {
    coords = -17.50000 -10.50000 0.00000;
    type = impulse;
    dir = 1 0 0;
    func = file;
    time_file = "msf/m0002_x.txt";
    amplitude = 1.0;
};

source {
    coords = -17.50000 -10.50000 0.00000;
    type = impulse;
    dir = 0 1 0;
    func = file;
    time_file = "msf/m0002_y.txt";
    amplitude = 1.0;
};

source {
    coords = -17.50000 -10.50000 0.00000;
    type = impulse;
    dir = 0 0 1;
    func = file;
    time_file = "msf/m0002_z.txt";
    amplitude = 1.0;
};

source {
    coords = -17.50000 -7.00000 0.00000;
    type = impulse;
    dir = 1 0 0;
    func = file;
    time_file = "msf/m0003_x.txt";
    amplitude = 1.0;
};

source {
    coords = -17.50000 -7.00000 0.00000;
    type = impulse;
    dir = 0 1 0;
    func = file;
    time_file = "msf/m0003_y.txt";
    amplitude = 1.0;
};

source {
    coords = -17.50000 -7.00000 0.00000;
    type = impulse;
    dir = 0 0 1;
    func = file;
    time_file = "msf/m0003_z.txt";
    amplitude = 1.0;
};

source {
    coords = -17.50000 -3.50000 0.00000;
    type = impulse;
    dir = 1 0 0;
    func = file;
    time_file = "msf/m0004_x.txt";
    amplitude = 1.0;
};

source {
    coords = -17.50000 -3.50000 0.00000;
    type = impulse;
    dir = 0 1 0;
    func = file;
    time_file = "msf/m0004_y.txt";
    amplitude = 1.0;
};

source {
    coords = -17.50000 -3.50000 0.00000;
    type = impulse;
    dir = 0 0 1;
    func = file;
    time_file = "msf/m0004_z.txt";
    amplitude = 1.0;
};

source {
    coords = -17.50000 0.00000 0.00000;
    type = impulse;
    dir = 1 0 0;
    func = file;
    time_file = "msf/m0005_x.txt";
    amplitude = 1.0;
};

source {
    coords = -17.50000 0.00000 0.00000;
    type = impulse;
    dir = 0 1 0;
    func = file;
    time_file = "msf/m0005_y.txt";
    amplitude = 1.0;
};

source {
    coords = -17.50000 0.00000 0.00000;
    type = impulse;
    dir = 0 0 1;
    func = file;
    time_file = "msf/m0005_z.txt";
    amplitude = 1.0;
};

source {
    coords = -17.50000 3.50000 0.00000;
    type = impulse;
    dir = 1 0 0;
    func = file;
    time_file = "msf/m0006_x.txt";
    amplitude = 1.0;
};

source {
    coords = -17.50000 3.50000 0.00000;
    type = impulse;
    dir = 0 1 0;
    func = file;
    time_file = "msf/m0006_y.txt";
    amplitude = 1.0;
};

source {
    coords = -17.50000 3.50000 0.00000;
    type = impulse;
    dir = 0 0 1;
    func = file;
    time_file = "msf/m0006_z.txt";
    amplitude = 1.0;
};

source {
    coords = -17.50000 7.00000 0.00000;
    type = impulse;
    dir = 1 0 0;
    func = file;
    time_file = "msf/m0007_x.txt";
    amplitude = 1.0;
};

source {
    coords = -17.50000 7.00000 0.00000;
    type = impulse;
    dir = 0 1 0;
    func = file;
    time_file = "msf/m0007_y.txt";
    amplitude = 1.0;
};

source {
    coords = -17.50000 7.00000 0.00000;
    type = impulse;
    dir = 0 0 1;
    func = file;
    time_file = "msf/m0007_z.txt";
    amplitude = 1.0;
};

source {
    coords = -17.50000 10.50000 0.00000;
    type = impulse;
    dir = 1 0 0;
    func = file;
    time_file = "msf/m0008_x.txt";
    amplitude = 1.0;
};

source {
    coords = -17.50000 10.50000 0.00000;
    type = impulse;
    dir = 0 1 0;
    func = file;
    time_file = "msf/m0008_y.txt";
    amplitude = 1.0;
};

source {
    coords = -17.50000 10.50000 0.00000;
    type = impulse;
    dir = 0 0 1;
    func = file;
    time_file = "msf/m0008_z.txt";
    amplitude = 1.0;
};

source {
    coords = -17.50000 14.00000 0.00000;
    type = impulse;
    dir = 1 0 0;
    func = file;
    time_file = "msf/m0009_x.txt";
    amplitude = 1.0;
};

source {
    coords = -17.50000 14.00000 0.00000;
    type = impulse;
    dir = 0 1 0;
    func = file;
    time_file = "msf/m0009_y.txt";
    amplitude = 1.0;
};

source {
    coords = -17.50000 14.00000 0.00000;
    type = impulse;
    dir = 0 0 1;
    func = file;
    time_file = "msf/m0009_z.txt";
    amplitude = 1.0;
};

source {
    coords = -17.50000 17.50000 0.00000;
    type = impulse;
    dir = 1 0 0;
    func = file;
    time_file = "msf/m0010_x.txt";
    amplitude = 1.0;
};

source {
    coords = -17.50000 17.50000 0.00000;
    type = impulse;
    dir = 0 1 0;
    func = file;
    time_file = "msf/m0010_y.txt";
    amplitude = 1.0;
};

source {
    coords = -17.50000 17.50000 0.00000;
    type = impulse;
    dir = 0 0 1;
    func = file;
    time_file = "msf/m0010_z.txt";
    amplitude = 1.0;
};

source {
    coords = -14.00000 -17.50000 0.00000;
    type = impulse;
    dir = 1 0 0;
    func = file;
    time_file = "msf/m0011_x.txt";
    amplitude = 1.0;
};

source {
    coords = -14.00000 -17.50000 0.00000;
    type = impulse;
    dir = 0 1 0;
    func = file;
    time_file = "msf/m0011_y.txt";
    amplitude = 1.0;
};

source {
    coords = -14.00000 -17.50000 0.00000;
    type = impulse;
    dir = 0 0 1;
    func = file;
    time_file = "msf/m0011_z.txt";
    amplitude = 1.0;
};

source {
    coords = -14.00000 -14.00000 0.00000;
    type = impulse;
    dir = 1 0 0;
    func = file;
    time_file = "msf/m0012_x.txt";
    amplitude = 1.0;
};

source {
    coords = -14.00000 -14.00000 0.00000;
    type = impulse;
    dir = 0 1 0;
    func = file;
    time_file = "msf/m0012_y.txt";
    amplitude = 1.0;
};

source {
    coords = -14.00000 -14.00000 0.00000;
    type = impulse;
    dir = 0 0 1;
    func = file;
    time_file = "msf/m0012_z.txt";
    amplitude = 1.0;
};

source {
    coords = -14.00000 -10.50000 0.00000;
    type = impulse;
    dir = 1 0 0;
    func = file;
    time_file = "msf/m0013_x.txt";
    amplitude = 1.0;
};

source {
    coords = -14.00000 -10.50000 0.00000;
    type = impulse;
    dir = 0 1 0;
    func = file;
    time_file = "msf/m0013_y.txt";
    amplitude = 1.0;
};

source {
    coords = -14.00000 -10.50000 0.00000;
    type = impulse;
    dir = 0 0 1;
    func = file;
    time_file = "msf/m0013_z.txt";
    amplitude = 1.0;
};

source {
    coords = -14.00000 -7.00000 0.00000;
    type = impulse;
    dir = 1 0 0;
    func = file;
    time_file = "msf/m0014_x.txt";
    amplitude = 1.0;
};

source {
    coords = -14.00000 -7.00000 0.00000;
    type = impulse;
    dir = 0 1 0;
    func = file;
    time_file = "msf/m0014_y.txt";
    amplitude = 1.0;
};

source {
    coords = -14.00000 -7.00000 0.00000;
    type = impulse;
    dir = 0 0 1;
    func = file;
    time_file = "msf/m0014_z.txt";
    amplitude = 1.0;
};

source {
    coords = -14.00000 -3.50000 0.00000;
    type = impulse;
    dir = 1 0 0;
    func = file;
    time_file = "msf/m0015_x.txt";
    amplitude = 1.0;
};

source {
    coords = -14.00000 -3.50000 0.00000;
    type = impulse;
    dir = 0 1 0;
    func = file;
    time_file = "msf/m0015_y.txt";
    amplitude = 1.0;
};

source {
    coords = -14.00000 -3.50000 0.00000;
    type = impulse;
    dir = 0 0 1;
    func = file;
    time_file = "msf/m0015_z.txt";
    amplitude = 1.0;
};

source {
    coords = -14.00000 0.00000 0.00000;
    type = impulse;
    dir = 1 0 0;
    func = file;
    time_file = "msf/m0016_x.txt";
    amplitude = 1.0;
};

source {
    coords = -14.00000 0.00000 0.00000;
    type = impulse;
    dir = 0 1 0;
    func = file;
    time_file = "msf/m0016_y.txt";
    amplitude = 1.0;
};

source {
    coords = -14.00000 0.00000 0.00000;
    type = impulse;
    dir = 0 0 1;
    func = file;
    time_file = "msf/m0016_z.txt";
    amplitude = 1.0;
};

source {
    coords = -14.00000 3.50000 0.00000;
    type = impulse;
    dir = 1 0 0;
    func = file;
    time_file = "msf/m0017_x.txt";
    amplitude = 1.0;
};

source {
    coords = -14.00000 3.50000 0.00000;
    type = impulse;
    dir = 0 1 0;
    func = file;
    time_file = "msf/m0017_y.txt";
    amplitude = 1.0;
};

source {
    coords = -14.00000 3.50000 0.00000;
    type = impulse;
    dir = 0 0 1;
    func = file;
    time_file = "msf/m0017_z.txt";
    amplitude = 1.0;
};

source {
    coords = -14.00000 7.00000 0.00000;
    type = impulse;
    dir = 1 0 0;
    func = file;
    time_file = "msf/m0018_x.txt";
    amplitude = 1.0;
};

source {
    coords = -14.00000 7.00000 0.00000;
    type = impulse;
    dir = 0 1 0;
    func = file;
    time_file = "msf/m0018_y.txt";
    amplitude = 1.0;
};

source {
    coords = -14.00000 7.00000 0.00000;
    type = impulse;
    dir = 0 0 1;
    func = file;
    time_file = "msf/m0018_z.txt";
    amplitude = 1.0;
};

source {
    coords = -14.00000 10.50000 0.00000;
    type = impulse;
    dir = 1 0 0;
    func = file;
    time_file = "msf/m0019_x.txt";
    amplitude = 1.0;
};

source {
    coords = -14.00000 10.50000 0.00000;
    type = impulse;
    dir = 0 1 0;
    func = file;
    time_file = "msf/m0019_y.txt";
    amplitude = 1.0;
};

source {
    coords = -14.00000 10.50000 0.00000;
    type = impulse;
    dir = 0 0 1;
    func = file;
    time_file = "msf/m0019_z.txt";
    amplitude = 1.0;
};

source {
    coords = -14.00000 14.00000 0.00000;
    type = impulse;
    dir = 1 0 0;
    func = file;
    time_file = "msf/m0020_x.txt";
    amplitude = 1.0;
};

source {
    coords = -14.00000 14.00000 0.00000;
    type = impulse;
    dir = 0 1 0;
    func = file;
    time_file = "msf/m0020_y.txt";
    amplitude = 1.0;
};

source {
    coords = -14.00000 14.00000 0.00000;
    type = impulse;
    dir = 0 0 1;
    func = file;
    time_file = "msf/m0020_z.txt";
    amplitude = 1.0;
};

source {
    coords = -14.00000 17.50000 0.00000;
    type = impulse;
    dir = 1 0 0;
    func = file;
    time_file = "msf/m0021_x.txt";
    amplitude = 1.0;
};

source {
    coords = -14.00000 17.50000 0.00000;
    type = impulse;
    dir = 0 1 0;
    func = file;
    time_file = "msf/m0021_y.txt";
    amplitude = 1.0;
};

source {
    coords = -14.00000 17.50000 0.00000;
    type = impulse;
    dir = 0 0 1;
    func = file;
    time_file = "msf/m0021_z.txt";
    amplitude = 1.0;
};

source {
    coords = -10.50000 -17.50000 0.00000;
    type = impulse;
    dir = 1 0 0;
    func = file;
    time_file = "msf/m0022_x.txt";
    amplitude = 1.0;
};

source {
    coords = -10.50000 -17.50000 0.00000;
    type = impulse;
    dir = 0 1 0;
    func = file;
    time_file = "msf/m0022_y.txt";
    amplitude = 1.0;
};

source {
    coords = -10.50000 -17.50000 0.00000;
    type = impulse;
    dir = 0 0 1;
    func = file;
    time_file = "msf/m0022_z.txt";
    amplitude = 1.0;
};

source {
    coords = -10.50000 -14.00000 0.00000;
    type = impulse;
    dir = 1 0 0;
    func = file;
    time_file = "msf/m0023_x.txt";
    amplitude = 1.0;
};

source {
    coords = -10.50000 -14.00000 0.00000;
    type = impulse;
    dir = 0 1 0;
    func = file;
    time_file = "msf/m0023_y.txt";
    amplitude = 1.0;
};

source {
    coords = -10.50000 -14.00000 0.00000;
    type = impulse;
    dir = 0 0 1;
    func = file;
    time_file = "msf/m0023_z.txt";
    amplitude = 1.0;
};

source {
    coords = -10.50000 -10.50000 0.00000;
    type = impulse;
    dir = 1 0 0;
    func = file;
    time_file = "msf/m0024_x.txt";
    amplitude = 1.0;
};

source {
    coords = -10.50000 -10.50000 0.00000;
    type = impulse;
    dir = 0 1 0;
    func = file;
    time_file = "msf/m0024_y.txt";
    amplitude = 1.0;
};

source {
    coords = -10.50000 -10.50000 0.00000;
    type = impulse;
    dir = 0 0 1;
    func = file;
    time_file = "msf/m0024_z.txt";
    amplitude = 1.0;
};

source {
    coords = -10.50000 -7.00000 0.00000;
    type = impulse;
    dir = 1 0 0;
    func = file;
    time_file = "msf/m0025_x.txt";
    amplitude = 1.0;
};

source {
    coords = -10.50000 -7.00000 0.00000;
    type = impulse;
    dir = 0 1 0;
    func = file;
    time_file = "msf/m0025_y.txt";
    amplitude = 1.0;
};

source {
    coords = -10.50000 -7.00000 0.00000;
    type = impulse;
    dir = 0 0 1;
    func = file;
    time_file = "msf/m0025_z.txt";
    amplitude = 1.0;
};

source {
    coords = -10.50000 -3.50000 0.00000;
    type = impulse;
    dir = 1 0 0;
    func = file;
    time_file = "msf/m0026_x.txt";
    amplitude = 1.0;
};

source {
    coords = -10.50000 -3.50000 0.00000;
    type = impulse;
    dir = 0 1 0;
    func = file;
    time_file = "msf/m0026_y.txt";
    amplitude = 1.0;
};

source {
    coords = -10.50000 -3.50000 0.00000;
    type = impulse;
    dir = 0 0 1;
    func = file;
    time_file = "msf/m0026_z.txt";
    amplitude = 1.0;
};

source {
    coords = -10.50000 0.00000 0.00000;
    type = impulse;
    dir = 1 0 0;
    func = file;
    time_file = "msf/m0027_x.txt";
    amplitude = 1.0;
};

source {
    coords = -10.50000 0.00000 0.00000;
    type = impulse;
    dir = 0 1 0;
    func = file;
    time_file = "msf/m0027_y.txt";
    amplitude = 1.0;
};

source {
    coords = -10.50000 0.00000 0.00000;
    type = impulse;
    dir = 0 0 1;
    func = file;
    time_file = "msf/m0027_z.txt";
    amplitude = 1.0;
};

source {
    coords = -10.50000 3.50000 0.00000;
    type = impulse;
    dir = 1 0 0;
    func = file;
    time_file = "msf/m0028_x.txt";
    amplitude = 1.0;
};

source {
    coords = -10.50000 3.50000 0.00000;
    type = impulse;
    dir = 0 1 0;
    func = file;
    time_file = "msf/m0028_y.txt";
    amplitude = 1.0;
};

source {
    coords = -10.50000 3.50000 0.00000;
    type = impulse;
    dir = 0 0 1;
    func = file;
    time_file = "msf/m0028_z.txt";
    amplitude = 1.0;
};

source {
    coords = -10.50000 7.00000 0.00000;
    type = impulse;
    dir = 1 0 0;
    func = file;
    time_file = "msf/m0029_x.txt";
    amplitude = 1.0;
};

source {
    coords = -10.50000 7.00000 0.00000;
    type = impulse;
    dir = 0 1 0;
    func = file;
    time_file = "msf/m0029_y.txt";
    amplitude = 1.0;
};

source {
    coords = -10.50000 7.00000 0.00000;
    type = impulse;
    dir = 0 0 1;
    func = file;
    time_file = "msf/m0029_z.txt";
    amplitude = 1.0;
};

source {
    coords = -10.50000 10.50000 0.00000;
    type = impulse;
    dir = 1 0 0;
    func = file;
    time_file = "msf/m0030_x.txt";
    amplitude = 1.0;
};

source {
    coords = -10.50000 10.50000 0.00000;
    type = impulse;
    dir = 0 1 0;
    func = file;
    time_file = "msf/m0030_y.txt";
    amplitude = 1.0;
};

source {
    coords = -10.50000 10.50000 0.00000;
    type = impulse;
    dir = 0 0 1;
    func = file;
    time_file = "msf/m0030_z.txt";
    amplitude = 1.0;
};

source {
    coords = -10.50000 14.00000 0.00000;
    type = impulse;
    dir = 1 0 0;
    func = file;
    time_file = "msf/m0031_x.txt";
    amplitude = 1.0;
};

source {
    coords = -10.50000 14.00000 0.00000;
    type = impulse;
    dir = 0 1 0;
    func = file;
    time_file = "msf/m0031_y.txt";
    amplitude = 1.0;
};

source {
    coords = -10.50000 14.00000 0.00000;
    type = impulse;
    dir = 0 0 1;
    func = file;
    time_file = "msf/m0031_z.txt";
    amplitude = 1.0;
};

source {
    coords = -10.50000 17.50000 0.00000;
    type = impulse;
    dir = 1 0 0;
    func = file;
    time_file = "msf/m0032_x.txt";
    amplitude = 1.0;
};

source {
    coords = -10.50000 17.50000 0.00000;
    type = impulse;
    dir = 0 1 0;
    func = file;
    time_file = "msf/m0032_y.txt";
    amplitude = 1.0;
};

source {
    coords = -10.50000 17.50000 0.00000;
    type = impulse;
    dir = 0 0 1;
    func = file;
    time_file = "msf/m0032_z.txt";
    amplitude = 1.0;
};

source {
    coords = -7.00000 -17.50000 0.00000;
    type = impulse;
    dir = 1 0 0;
    func = file;
    time_file = "msf/m0033_x.txt";
    amplitude = 1.0;
};

source {
    coords = -7.00000 -17.50000 0.00000;
    type = impulse;
    dir = 0 1 0;
    func = file;
    time_file = "msf/m0033_y.txt";
    amplitude = 1.0;
};

source {
    coords = -7.00000 -17.50000 0.00000;
    type = impulse;
    dir = 0 0 1;
    func = file;
    time_file = "msf/m0033_z.txt";
    amplitude = 1.0;
};

source {
    coords = -7.00000 -14.00000 0.00000;
    type = impulse;
    dir = 1 0 0;
    func = file;
    time_file = "msf/m0034_x.txt";
    amplitude = 1.0;
};

source {
    coords = -7.00000 -14.00000 0.00000;
    type = impulse;
    dir = 0 1 0;
    func = file;
    time_file = "msf/m0034_y.txt";
    amplitude = 1.0;
};

source {
    coords = -7.00000 -14.00000 0.00000;
    type = impulse;
    dir = 0 0 1;
    func = file;
    time_file = "msf/m0034_z.txt";
    amplitude = 1.0;
};

source {
    coords = -7.00000 -10.50000 0.00000;
    type = impulse;
    dir = 1 0 0;
    func = file;
    time_file = "msf/m0035_x.txt";
    amplitude = 1.0;
};

source {
    coords = -7.00000 -10.50000 0.00000;
    type = impulse;
    dir = 0 1 0;
    func = file;
    time_file = "msf/m0035_y.txt";
    amplitude = 1.0;
};

source {
    coords = -7.00000 -10.50000 0.00000;
    type = impulse;
    dir = 0 0 1;
    func = file;
    time_file = "msf/m0035_z.txt";
    amplitude = 1.0;
};

source {
    coords = -7.00000 -7.00000 0.00000;
    type = impulse;
    dir = 1 0 0;
    func = file;
    time_file = "msf/m0036_x.txt";
    amplitude = 1.0;
};

source {
    coords = -7.00000 -7.00000 0.00000;
    type = impulse;
    dir = 0 1 0;
    func = file;
    time_file = "msf/m0036_y.txt";
    amplitude = 1.0;
};

source {
    coords = -7.00000 -7.00000 0.00000;
    type = impulse;
    dir = 0 0 1;
    func = file;
    time_file = "msf/m0036_z.txt";
    amplitude = 1.0;
};

source {
    coords = -7.00000 -3.50000 0.00000;
    type = impulse;
    dir = 1 0 0;
    func = file;
    time_file = "msf/m0037_x.txt";
    amplitude = 1.0;
};

source {
    coords = -7.00000 -3.50000 0.00000;
    type = impulse;
    dir = 0 1 0;
    func = file;
    time_file = "msf/m0037_y.txt";
    amplitude = 1.0;
};

source {
    coords = -7.00000 -3.50000 0.00000;
    type = impulse;
    dir = 0 0 1;
    func = file;
    time_file = "msf/m0037_z.txt";
    amplitude = 1.0;
};

source {
    coords = -7.00000 0.00000 0.00000;
    type = impulse;
    dir = 1 0 0;
    func = file;
    time_file = "msf/m0038_x.txt";
    amplitude = 1.0;
};

source {
    coords = -7.00000 0.00000 0.00000;
    type = impulse;
    dir = 0 1 0;
    func = file;
    time_file = "msf/m0038_y.txt";
    amplitude = 1.0;
};

source {
    coords = -7.00000 0.00000 0.00000;
    type = impulse;
    dir = 0 0 1;
    func = file;
    time_file = "msf/m0038_z.txt";
    amplitude = 1.0;
};

source {
    coords = -7.00000 3.50000 0.00000;
    type = impulse;
    dir = 1 0 0;
    func = file;
    time_file = "msf/m0039_x.txt";
    amplitude = 1.0;
};

source {
    coords = -7.00000 3.50000 0.00000;
    type = impulse;
    dir = 0 1 0;
    func = file;
    time_file = "msf/m0039_y.txt";
    amplitude = 1.0;
};

source {
    coords = -7.00000 3.50000 0.00000;
    type = impulse;
    dir = 0 0 1;
    func = file;
    time_file = "msf/m0039_z.txt";
    amplitude = 1.0;
};

source {
    coords = -7.00000 7.00000 0.00000;
    type = impulse;
    dir = 1 0 0;
    func = file;
    time_file = "msf/m0040_x.txt";
    amplitude = 1.0;
};

source {
    coords = -7.00000 7.00000 0.00000;
    type = impulse;
    dir = 0 1 0;
    func = file;
    time_file = "msf/m0040_y.txt";
    amplitude = 1.0;
};

source {
    coords = -7.00000 7.00000 0.00000;
    type = impulse;
    dir = 0 0 1;
    func = file;
    time_file = "msf/m0040_z.txt";
    amplitude = 1.0;
};

source {
    coords = -7.00000 10.50000 0.00000;
    type = impulse;
    dir = 1 0 0;
    func = file;
    time_file = "msf/m0041_x.txt";
    amplitude = 1.0;
};

source {
    coords = -7.00000 10.50000 0.00000;
    type = impulse;
    dir = 0 1 0;
    func = file;
    time_file = "msf/m0041_y.txt";
    amplitude = 1.0;
};

source {
    coords = -7.00000 10.50000 0.00000;
    type = impulse;
    dir = 0 0 1;
    func = file;
    time_file = "msf/m0041_z.txt";
    amplitude = 1.0;
};

source {
    coords = -7.00000 14.00000 0.00000;
    type = impulse;
    dir = 1 0 0;
    func = file;
    time_file = "msf/m0042_x.txt";
    amplitude = 1.0;
};

source {
    coords = -7.00000 14.00000 0.00000;
    type = impulse;
    dir = 0 1 0;
    func = file;
    time_file = "msf/m0042_y.txt";
    amplitude = 1.0;
};

source {
    coords = -7.00000 14.00000 0.00000;
    type = impulse;
    dir = 0 0 1;
    func = file;
    time_file = "msf/m0042_z.txt";
    amplitude = 1.0;
};

source {
    coords = -7.00000 17.50000 0.00000;
    type = impulse;
    dir = 1 0 0;
    func = file;
    time_file = "msf/m0043_x.txt";
    amplitude = 1.0;
};

source {
    coords = -7.00000 17.50000 0.00000;
    type = impulse;
    dir = 0 1 0;
    func = file;
    time_file = "msf/m0043_y.txt";
    amplitude = 1.0;
};

source {
    coords = -7.00000 17.50000 0.00000;
    type = impulse;
    dir = 0 0 1;
    func = file;
    time_file = "msf/m0043_z.txt";
    amplitude = 1.0;
};

source {
    coords = -3.50000 -17.50000 0.00000;
    type = impulse;
    dir = 1 0 0;
    func = file;
    time_file = "msf/m0044_x.txt";
    amplitude = 1.0;
};

source {
    coords = -3.50000 -17.50000 0.00000;
    type = impulse;
    dir = 0 1 0;
    func = file;
    time_file = "msf/m0044_y.txt";
    amplitude = 1.0;
};

source {
    coords = -3.50000 -17.50000 0.00000;
    type = impulse;
    dir = 0 0 1;
    func = file;
    time_file = "msf/m0044_z.txt";
    amplitude = 1.0;
};

source {
    coords = -3.50000 -14.00000 0.00000;
    type = impulse;
    dir = 1 0 0;
    func = file;
    time_file = "msf/m0045_x.txt";
    amplitude = 1.0;
};

source {
    coords = -3.50000 -14.00000 0.00000;
    type = impulse;
    dir = 0 1 0;
    func = file;
    time_file = "msf/m0045_y.txt";
    amplitude = 1.0;
};

source {
    coords = -3.50000 -14.00000 0.00000;
    type = impulse;
    dir = 0 0 1;
    func = file;
    time_file = "msf/m0045_z.txt";
    amplitude = 1.0;
};

source {
    coords = -3.50000 -10.50000 0.00000;
    type = impulse;
    dir = 1 0 0;
    func = file;
    time_file = "msf/m0046_x.txt";
    amplitude = 1.0;
};

source {
    coords = -3.50000 -10.50000 0.00000;
    type = impulse;
    dir = 0 1 0;
    func = file;
    time_file = "msf/m0046_y.txt";
    amplitude = 1.0;
};

source {
    coords = -3.50000 -10.50000 0.00000;
    type = impulse;
    dir = 0 0 1;
    func = file;
    time_file = "msf/m0046_z.txt";
    amplitude = 1.0;
};

source {
    coords = -3.50000 -7.00000 0.00000;
    type = impulse;
    dir = 1 0 0;
    func = file;
    time_file = "msf/m0047_x.txt";
    amplitude = 1.0;
};

source {
    coords = -3.50000 -7.00000 0.00000;
    type = impulse;
    dir = 0 1 0;
    func = file;
    time_file = "msf/m0047_y.txt";
    amplitude = 1.0;
};

source {
    coords = -3.50000 -7.00000 0.00000;
    type = impulse;
    dir = 0 0 1;
    func = file;
    time_file = "msf/m0047_z.txt";
    amplitude = 1.0;
};

source {
    coords = -3.50000 -3.50000 0.00000;
    type = impulse;
    dir = 1 0 0;
    func = file;
    time_file = "msf/m0048_x.txt";
    amplitude = 1.0;
};

source {
    coords = -3.50000 -3.50000 0.00000;
    type = impulse;
    dir = 0 1 0;
    func = file;
    time_file = "msf/m0048_y.txt";
    amplitude = 1.0;
};

source {
    coords = -3.50000 -3.50000 0.00000;
    type = impulse;
    dir = 0 0 1;
    func = file;
    time_file = "msf/m0048_z.txt";
    amplitude = 1.0;
};

source {
    coords = -3.50000 0.00000 0.00000;
    type = impulse;
    dir = 1 0 0;
    func = file;
    time_file = "msf/m0049_x.txt";
    amplitude = 1.0;
};

source {
    coords = -3.50000 0.00000 0.00000;
    type = impulse;
    dir = 0 1 0;
    func = file;
    time_file = "msf/m0049_y.txt";
    amplitude = 1.0;
};

source {
    coords = -3.50000 0.00000 0.00000;
    type = impulse;
    dir = 0 0 1;
    func = file;
    time_file = "msf/m0049_z.txt";
    amplitude = 1.0;
};

source {
    coords = -3.50000 3.50000 0.00000;
    type = impulse;
    dir = 1 0 0;
    func = file;
    time_file = "msf/m0050_x.txt";
    amplitude = 1.0;
};

source {
    coords = -3.50000 3.50000 0.00000;
    type = impulse;
    dir = 0 1 0;
    func = file;
    time_file = "msf/m0050_y.txt";
    amplitude = 1.0;
};

source {
    coords = -3.50000 3.50000 0.00000;
    type = impulse;
    dir = 0 0 1;
    func = file;
    time_file = "msf/m0050_z.txt";
    amplitude = 1.0;
};

source {
    coords = -3.50000 7.00000 0.00000;
    type = impulse;
    dir = 1 0 0;
    func = file;
    time_file = "msf/m0051_x.txt";
    amplitude = 1.0;
};

source {
    coords = -3.50000 7.00000 0.00000;
    type = impulse;
    dir = 0 1 0;
    func = file;
    time_file = "msf/m0051_y.txt";
    amplitude = 1.0;
};

source {
    coords = -3.50000 7.00000 0.00000;
    type = impulse;
    dir = 0 0 1;
    func = file;
    time_file = "msf/m0051_z.txt";
    amplitude = 1.0;
};

source {
    coords = -3.50000 10.50000 0.00000;
    type = impulse;
    dir = 1 0 0;
    func = file;
    time_file = "msf/m0052_x.txt";
    amplitude = 1.0;
};

source {
    coords = -3.50000 10.50000 0.00000;
    type = impulse;
    dir = 0 1 0;
    func = file;
    time_file = "msf/m0052_y.txt";
    amplitude = 1.0;
};

source {
    coords = -3.50000 10.50000 0.00000;
    type = impulse;
    dir = 0 0 1;
    func = file;
    time_file = "msf/m0052_z.txt";
    amplitude = 1.0;
};

source {
    coords = -3.50000 14.00000 0.00000;
    type = impulse;
    dir = 1 0 0;
    func = file;
    time_file = "msf/m0053_x.txt";
    amplitude = 1.0;
};

source {
    coords = -3.50000 14.00000 0.00000;
    type = impulse;
    dir = 0 1 0;
    func = file;
    time_file = "msf/m0053_y.txt";
    amplitude = 1.0;
};

source {
    coords = -3.50000 14.00000 0.00000;
    type = impulse;
    dir = 0 0 1;
    func = file;
    time_file = "msf/m0053_z.txt";
    amplitude = 1.0;
};

source {
    coords = -3.50000 17.50000 0.00000;
    type = impulse;
    dir = 1 0 0;
    func = file;
    time_file = "msf/m0054_x.txt";
    amplitude = 1.0;
};

source {
    coords = -3.50000 17.50000 0.00000;
    type = impulse;
    dir = 0 1 0;
    func = file;
    time_file = "msf/m0054_y.txt";
    amplitude = 1.0;
};

source {
    coords = -3.50000 17.50000 0.00000;
    type = impulse;
    dir = 0 0 1;
    func = file;
    time_file = "msf/m0054_z.txt";
    amplitude = 1.0;
};

source {
    coords = 0.00000 -17.50000 0.00000;
    type = impulse;
    dir = 1 0 0;
    func = file;
    time_file = "msf/m0055_x.txt";
    amplitude = 1.0;
};

source {
    coords = 0.00000 -17.50000 0.00000;
    type = impulse;
    dir = 0 1 0;
    func = file;
    time_file = "msf/m0055_y.txt";
    amplitude = 1.0;
};

source {
    coords = 0.00000 -17.50000 0.00000;
    type = impulse;
    dir = 0 0 1;
    func = file;
    time_file = "msf/m0055_z.txt";
    amplitude = 1.0;
};

source {
    coords = 0.00000 -14.00000 0.00000;
    type = impulse;
    dir = 1 0 0;
    func = file;
    time_file = "msf/m0056_x.txt";
    amplitude = 1.0;
};

source {
    coords = 0.00000 -14.00000 0.00000;
    type = impulse;
    dir = 0 1 0;
    func = file;
    time_file = "msf/m0056_y.txt";
    amplitude = 1.0;
};

source {
    coords = 0.00000 -14.00000 0.00000;
    type = impulse;
    dir = 0 0 1;
    func = file;
    time_file = "msf/m0056_z.txt";
    amplitude = 1.0;
};

source {
    coords = 0.00000 -10.50000 0.00000;
    type = impulse;
    dir = 1 0 0;
    func = file;
    time_file = "msf/m0057_x.txt";
    amplitude = 1.0;
};

source {
    coords = 0.00000 -10.50000 0.00000;
    type = impulse;
    dir = 0 1 0;
    func = file;
    time_file = "msf/m0057_y.txt";
    amplitude = 1.0;
};

source {
    coords = 0.00000 -10.50000 0.00000;
    type = impulse;
    dir = 0 0 1;
    func = file;
    time_file = "msf/m0057_z.txt";
    amplitude = 1.0;
};

source {
    coords = 0.00000 -7.00000 0.00000;
    type = impulse;
    dir = 1 0 0;
    func = file;
    time_file = "msf/m0058_x.txt";
    amplitude = 1.0;
};

source {
    coords = 0.00000 -7.00000 0.00000;
    type = impulse;
    dir = 0 1 0;
    func = file;
    time_file = "msf/m0058_y.txt";
    amplitude = 1.0;
};

source {
    coords = 0.00000 -7.00000 0.00000;
    type = impulse;
    dir = 0 0 1;
    func = file;
    time_file = "msf/m0058_z.txt";
    amplitude = 1.0;
};

source {
    coords = 0.00000 -3.50000 0.00000;
    type = impulse;
    dir = 1 0 0;
    func = file;
    time_file = "msf/m0059_x.txt";
    amplitude = 1.0;
};

source {
    coords = 0.00000 -3.50000 0.00000;
    type = impulse;
    dir = 0 1 0;
    func = file;
    time_file = "msf/m0059_y.txt";
    amplitude = 1.0;
};

source {
    coords = 0.00000 -3.50000 0.00000;
    type = impulse;
    dir = 0 0 1;
    func = file;
    time_file = "msf/m0059_z.txt";
    amplitude = 1.0;
};

source {
    coords = 0.00000 0.00000 0.00000;
    type = impulse;
    dir = 1 0 0;
    func = file;
    time_file = "msf/m0060_x.txt";
    amplitude = 1.0;
};

source {
    coords = 0.00000 0.00000 0.00000;
    type = impulse;
    dir = 0 1 0;
    func = file;
    time_file = "msf/m0060_y.txt";
    amplitude = 1.0;
};

source {
    coords = 0.00000 0.00000 0.00000;
    type = impulse;
    dir = 0 0 1;
    func = file;
    time_file = "msf/m0060_z.txt";
    amplitude = 1.0;
};

source {
    coords = 0.00000 3.50000 0.00000;
    type = impulse;
    dir = 1 0 0;
    func = file;
    time_file = "msf/m0061_x.txt";
    amplitude = 1.0;
};

source {
    coords = 0.00000 3.50000 0.00000;
    type = impulse;
    dir = 0 1 0;
    func = file;
    time_file = "msf/m0061_y.txt";
    amplitude = 1.0;
};

source {
    coords = 0.00000 3.50000 0.00000;
    type = impulse;
    dir = 0 0 1;
    func = file;
    time_file = "msf/m0061_z.txt";
    amplitude = 1.0;
};

source {
    coords = 0.00000 7.00000 0.00000;
    type = impulse;
    dir = 1 0 0;
    func = file;
    time_file = "msf/m0062_x.txt";
    amplitude = 1.0;
};

source {
    coords = 0.00000 7.00000 0.00000;
    type = impulse;
    dir = 0 1 0;
    func = file;
    time_file = "msf/m0062_y.txt";
    amplitude = 1.0;
};

source {
    coords = 0.00000 7.00000 0.00000;
    type = impulse;
    dir = 0 0 1;
    func = file;
    time_file = "msf/m0062_z.txt";
    amplitude = 1.0;
};

source {
    coords = 0.00000 10.50000 0.00000;
    type = impulse;
    dir = 1 0 0;
    func = file;
    time_file = "msf/m0063_x.txt";
    amplitude = 1.0;
};

source {
    coords = 0.00000 10.50000 0.00000;
    type = impulse;
    dir = 0 1 0;
    func = file;
    time_file = "msf/m0063_y.txt";
    amplitude = 1.0;
};

source {
    coords = 0.00000 10.50000 0.00000;
    type = impulse;
    dir = 0 0 1;
    func = file;
    time_file = "msf/m0063_z.txt";
    amplitude = 1.0;
};

source {
    coords = 0.00000 14.00000 0.00000;
    type = impulse;
    dir = 1 0 0;
    func = file;
    time_file = "msf/m0064_x.txt";
    amplitude = 1.0;
};

source {
    coords = 0.00000 14.00000 0.00000;
    type = impulse;
    dir = 0 1 0;
    func = file;
    time_file = "msf/m0064_y.txt";
    amplitude = 1.0;
};

source {
    coords = 0.00000 14.00000 0.00000;
    type = impulse;
    dir = 0 0 1;
    func = file;
    time_file = "msf/m0064_z.txt";
    amplitude = 1.0;
};

source {
    coords = 0.00000 17.50000 0.00000;
    type = impulse;
    dir = 1 0 0;
    func = file;
    time_file = "msf/m0065_x.txt";
    amplitude = 1.0;
};

source {
    coords = 0.00000 17.50000 0.00000;
    type = impulse;
    dir = 0 1 0;
    func = file;
    time_file = "msf/m0065_y.txt";
    amplitude = 1.0;
};

source {
    coords = 0.00000 17.50000 0.00000;
    type = impulse;
    dir = 0 0 1;
    func = file;
    time_file = "msf/m0065_z.txt";
    amplitude = 1.0;
};

source {
    coords = 3.50000 -17.50000 0.00000;
    type = impulse;
    dir = 1 0 0;
    func = file;
    time_file = "msf/m0066_x.txt";
    amplitude = 1.0;
};

source {
    coords = 3.50000 -17.50000 0.00000;
    type = impulse;
    dir = 0 1 0;
    func = file;
    time_file = "msf/m0066_y.txt";
    amplitude = 1.0;
};

source {
    coords = 3.50000 -17.50000 0.00000;
    type = impulse;
    dir = 0 0 1;
    func = file;
    time_file = "msf/m0066_z.txt";
    amplitude = 1.0;
};

source {
    coords = 3.50000 -14.00000 0.00000;
    type = impulse;
    dir = 1 0 0;
    func = file;
    time_file = "msf/m0067_x.txt";
    amplitude = 1.0;
};

source {
    coords = 3.50000 -14.00000 0.00000;
    type = impulse;
    dir = 0 1 0;
    func = file;
    time_file = "msf/m0067_y.txt";
    amplitude = 1.0;
};

source {
    coords = 3.50000 -14.00000 0.00000;
    type = impulse;
    dir = 0 0 1;
    func = file;
    time_file = "msf/m0067_z.txt";
    amplitude = 1.0;
};

source {
    coords = 3.50000 -10.50000 0.00000;
    type = impulse;
    dir = 1 0 0;
    func = file;
    time_file = "msf/m0068_x.txt";
    amplitude = 1.0;
};

source {
    coords = 3.50000 -10.50000 0.00000;
    type = impulse;
    dir = 0 1 0;
    func = file;
    time_file = "msf/m0068_y.txt";
    amplitude = 1.0;
};

source {
    coords = 3.50000 -10.50000 0.00000;
    type = impulse;
    dir = 0 0 1;
    func = file;
    time_file = "msf/m0068_z.txt";
    amplitude = 1.0;
};

source {
    coords = 3.50000 -7.00000 0.00000;
    type = impulse;
    dir = 1 0 0;
    func = file;
    time_file = "msf/m0069_x.txt";
    amplitude = 1.0;
};

source {
    coords = 3.50000 -7.00000 0.00000;
    type = impulse;
    dir = 0 1 0;
    func = file;
    time_file = "msf/m0069_y.txt";
    amplitude = 1.0;
};

source {
    coords = 3.50000 -7.00000 0.00000;
    type = impulse;
    dir = 0 0 1;
    func = file;
    time_file = "msf/m0069_z.txt";
    amplitude = 1.0;
};

source {
    coords = 3.50000 -3.50000 0.00000;
    type = impulse;
    dir = 1 0 0;
    func = file;
    time_file = "msf/m0070_x.txt";
    amplitude = 1.0;
};

source {
    coords = 3.50000 -3.50000 0.00000;
    type = impulse;
    dir = 0 1 0;
    func = file;
    time_file = "msf/m0070_y.txt";
    amplitude = 1.0;
};

source {
    coords = 3.50000 -3.50000 0.00000;
    type = impulse;
    dir = 0 0 1;
    func = file;
    time_file = "msf/m0070_z.txt";
    amplitude = 1.0;
};

source {
    coords = 3.50000 0.00000 0.00000;
    type = impulse;
    dir = 1 0 0;
    func = file;
    time_file = "msf/m0071_x.txt";
    amplitude = 1.0;
};

source {
    coords = 3.50000 0.00000 0.00000;
    type = impulse;
    dir = 0 1 0;
    func = file;
    time_file = "msf/m0071_y.txt";
    amplitude = 1.0;
};

source {
    coords = 3.50000 0.00000 0.00000;
    type = impulse;
    dir = 0 0 1;
    func = file;
    time_file = "msf/m0071_z.txt";
    amplitude = 1.0;
};

source {
    coords = 3.50000 3.50000 0.00000;
    type = impulse;
    dir = 1 0 0;
    func = file;
    time_file = "msf/m0072_x.txt";
    amplitude = 1.0;
};

source {
    coords = 3.50000 3.50000 0.00000;
    type = impulse;
    dir = 0 1 0;
    func = file;
    time_file = "msf/m0072_y.txt";
    amplitude = 1.0;
};

source {
    coords = 3.50000 3.50000 0.00000;
    type = impulse;
    dir = 0 0 1;
    func = file;
    time_file = "msf/m0072_z.txt";
    amplitude = 1.0;
};

source {
    coords = 3.50000 7.00000 0.00000;
    type = impulse;
    dir = 1 0 0;
    func = file;
    time_file = "msf/m0073_x.txt";
    amplitude = 1.0;
};

source {
    coords = 3.50000 7.00000 0.00000;
    type = impulse;
    dir = 0 1 0;
    func = file;
    time_file = "msf/m0073_y.txt";
    amplitude = 1.0;
};

source {
    coords = 3.50000 7.00000 0.00000;
    type = impulse;
    dir = 0 0 1;
    func = file;
    time_file = "msf/m0073_z.txt";
    amplitude = 1.0;
};

source {
    coords = 3.50000 10.50000 0.00000;
    type = impulse;
    dir = 1 0 0;
    func = file;
    time_file = "msf/m0074_x.txt";
    amplitude = 1.0;
};

source {
    coords = 3.50000 10.50000 0.00000;
    type = impulse;
    dir = 0 1 0;
    func = file;
    time_file = "msf/m0074_y.txt";
    amplitude = 1.0;
};

source {
    coords = 3.50000 10.50000 0.00000;
    type = impulse;
    dir = 0 0 1;
    func = file;
    time_file = "msf/m0074_z.txt";
    amplitude = 1.0;
};

source {
    coords = 3.50000 14.00000 0.00000;
    type = impulse;
    dir = 1 0 0;
    func = file;
    time_file = "msf/m0075_x.txt";
    amplitude = 1.0;
};

source {
    coords = 3.50000 14.00000 0.00000;
    type = impulse;
    dir = 0 1 0;
    func = file;
    time_file = "msf/m0075_y.txt";
    amplitude = 1.0;
};

source {
    coords = 3.50000 14.00000 0.00000;
    type = impulse;
    dir = 0 0 1;
    func = file;
    time_file = "msf/m0075_z.txt";
    amplitude = 1.0;
};

source {
    coords = 3.50000 17.50000 0.00000;
    type = impulse;
    dir = 1 0 0;
    func = file;
    time_file = "msf/m0076_x.txt";
    amplitude = 1.0;
};

source {
    coords = 3.50000 17.50000 0.00000;
    type = impulse;
    dir = 0 1 0;
    func = file;
    time_file = "msf/m0076_y.txt";
    amplitude = 1.0;
};

source {
    coords = 3.50000 17.50000 0.00000;
    type = impulse;
    dir = 0 0 1;
    func = file;
    time_file = "msf/m0076_z.txt";
    amplitude = 1.0;
};

source {
    coords = 7.00000 -17.50000 0.00000;
    type = impulse;
    dir = 1 0 0;
    func = file;
    time_file = "msf/m0077_x.txt";
    amplitude = 1.0;
};

source {
    coords = 7.00000 -17.50000 0.00000;
    type = impulse;
    dir = 0 1 0;
    func = file;
    time_file = "msf/m0077_y.txt";
    amplitude = 1.0;
};

source {
    coords = 7.00000 -17.50000 0.00000;
    type = impulse;
    dir = 0 0 1;
    func = file;
    time_file = "msf/m0077_z.txt";
    amplitude = 1.0;
};

source {
    coords = 7.00000 -14.00000 0.00000;
    type = impulse;
    dir = 1 0 0;
    func = file;
    time_file = "msf/m0078_x.txt";
    amplitude = 1.0;
};

source {
    coords = 7.00000 -14.00000 0.00000;
    type = impulse;
    dir = 0 1 0;
    func = file;
    time_file = "msf/m0078_y.txt";
    amplitude = 1.0;
};

source {
    coords = 7.00000 -14.00000 0.00000;
    type = impulse;
    dir = 0 0 1;
    func = file;
    time_file = "msf/m0078_z.txt";
    amplitude = 1.0;
};

source {
    coords = 7.00000 -10.50000 0.00000;
    type = impulse;
    dir = 1 0 0;
    func = file;
    time_file = "msf/m0079_x.txt";
    amplitude = 1.0;
};

source {
    coords = 7.00000 -10.50000 0.00000;
    type = impulse;
    dir = 0 1 0;
    func = file;
    time_file = "msf/m0079_y.txt";
    amplitude = 1.0;
};

source {
    coords = 7.00000 -10.50000 0.00000;
    type = impulse;
    dir = 0 0 1;
    func = file;
    time_file = "msf/m0079_z.txt";
    amplitude = 1.0;
};

source {
    coords = 7.00000 -7.00000 0.00000;
    type = impulse;
    dir = 1 0 0;
    func = file;
    time_file = "msf/m0080_x.txt";
    amplitude = 1.0;
};

source {
    coords = 7.00000 -7.00000 0.00000;
    type = impulse;
    dir = 0 1 0;
    func = file;
    time_file = "msf/m0080_y.txt";
    amplitude = 1.0;
};

source {
    coords = 7.00000 -7.00000 0.00000;
    type = impulse;
    dir = 0 0 1;
    func = file;
    time_file = "msf/m0080_z.txt";
    amplitude = 1.0;
};

source {
    coords = 7.00000 -3.50000 0.00000;
    type = impulse;
    dir = 1 0 0;
    func = file;
    time_file = "msf/m0081_x.txt";
    amplitude = 1.0;
};

source {
    coords = 7.00000 -3.50000 0.00000;
    type = impulse;
    dir = 0 1 0;
    func = file;
    time_file = "msf/m0081_y.txt";
    amplitude = 1.0;
};

source {
    coords = 7.00000 -3.50000 0.00000;
    type = impulse;
    dir = 0 0 1;
    func = file;
    time_file = "msf/m0081_z.txt";
    amplitude = 1.0;
};

source {
    coords = 7.00000 0.00000 0.00000;
    type = impulse;
    dir = 1 0 0;
    func = file;
    time_file = "msf/m0082_x.txt";
    amplitude = 1.0;
};

source {
    coords = 7.00000 0.00000 0.00000;
    type = impulse;
    dir = 0 1 0;
    func = file;
    time_file = "msf/m0082_y.txt";
    amplitude = 1.0;
};

source {
    coords = 7.00000 0.00000 0.00000;
    type = impulse;
    dir = 0 0 1;
    func = file;
    time_file = "msf/m0082_z.txt";
    amplitude = 1.0;
};

source {
    coords = 7.00000 3.50000 0.00000;
    type = impulse;
    dir = 1 0 0;
    func = file;
    time_file = "msf/m0083_x.txt";
    amplitude = 1.0;
};

source {
    coords = 7.00000 3.50000 0.00000;
    type = impulse;
    dir = 0 1 0;
    func = file;
    time_file = "msf/m0083_y.txt";
    amplitude = 1.0;
};

source {
    coords = 7.00000 3.50000 0.00000;
    type = impulse;
    dir = 0 0 1;
    func = file;
    time_file = "msf/m0083_z.txt";
    amplitude = 1.0;
};

source {
    coords = 7.00000 7.00000 0.00000;
    type = impulse;
    dir = 1 0 0;
    func = file;
    time_file = "msf/m0084_x.txt";
    amplitude = 1.0;
};

source {
    coords = 7.00000 7.00000 0.00000;
    type = impulse;
    dir = 0 1 0;
    func = file;
    time_file = "msf/m0084_y.txt";
    amplitude = 1.0;
};

source {
    coords = 7.00000 7.00000 0.00000;
    type = impulse;
    dir = 0 0 1;
    func = file;
    time_file = "msf/m0084_z.txt";
    amplitude = 1.0;
};

source {
    coords = 7.00000 10.50000 0.00000;
    type = impulse;
    dir = 1 0 0;
    func = file;
    time_file = "msf/m0085_x.txt";
    amplitude = 1.0;
};

source {
    coords = 7.00000 10.50000 0.00000;
    type = impulse;
    dir = 0 1 0;
    func = file;
    time_file = "msf/m0085_y.txt";
    amplitude = 1.0;
};

source {
    coords = 7.00000 10.50000 0.00000;
    type = impulse;
    dir = 0 0 1;
    func = file;
    time_file = "msf/m0085_z.txt";
    amplitude = 1.0;
};

source {
    coords = 7.00000 14.00000 0.00000;
    type = impulse;
    dir = 1 0 0;
    func = file;
    time_file = "msf/m0086_x.txt";
    amplitude = 1.0;
};

source {
    coords = 7.00000 14.00000 0.00000;
    type = impulse;
    dir = 0 1 0;
    func = file;
    time_file = "msf/m0086_y.txt";
    amplitude = 1.0;
};

source {
    coords = 7.00000 14.00000 0.00000;
    type = impulse;
    dir = 0 0 1;
    func = file;
    time_file = "msf/m0086_z.txt";
    amplitude = 1.0;
};

source {
    coords = 7.00000 17.50000 0.00000;
    type = impulse;
    dir = 1 0 0;
    func = file;
    time_file = "msf/m0087_x.txt";
    amplitude = 1.0;
};

source {
    coords = 7.00000 17.50000 0.00000;
    type = impulse;
    dir = 0 1 0;
    func = file;
    time_file = "msf/m0087_y.txt";
    amplitude = 1.0;
};

source {
    coords = 7.00000 17.50000 0.00000;
    type = impulse;
    dir = 0 0 1;
    func = file;
    time_file = "msf/m0087_z.txt";
    amplitude = 1.0;
};

source {
    coords = 10.50000 -17.50000 0.00000;
    type = impulse;
    dir = 1 0 0;
    func = file;
    time_file = "msf/m0088_x.txt";
    amplitude = 1.0;
};

source {
    coords = 10.50000 -17.50000 0.00000;
    type = impulse;
    dir = 0 1 0;
    func = file;
    time_file = "msf/m0088_y.txt";
    amplitude = 1.0;
};

source {
    coords = 10.50000 -17.50000 0.00000;
    type = impulse;
    dir = 0 0 1;
    func = file;
    time_file = "msf/m0088_z.txt";
    amplitude = 1.0;
};

source {
    coords = 10.50000 -14.00000 0.00000;
    type = impulse;
    dir = 1 0 0;
    func = file;
    time_file = "msf/m0089_x.txt";
    amplitude = 1.0;
};

source {
    coords = 10.50000 -14.00000 0.00000;
    type = impulse;
    dir = 0 1 0;
    func = file;
    time_file = "msf/m0089_y.txt";
    amplitude = 1.0;
};

source {
    coords = 10.50000 -14.00000 0.00000;
    type = impulse;
    dir = 0 0 1;
    func = file;
    time_file = "msf/m0089_z.txt";
    amplitude = 1.0;
};

source {
    coords = 10.50000 -10.50000 0.00000;
    type = impulse;
    dir = 1 0 0;
    func = file;
    time_file = "msf/m0090_x.txt";
    amplitude = 1.0;
};

source {
    coords = 10.50000 -10.50000 0.00000;
    type = impulse;
    dir = 0 1 0;
    func = file;
    time_file = "msf/m0090_y.txt";
    amplitude = 1.0;
};

source {
    coords = 10.50000 -10.50000 0.00000;
    type = impulse;
    dir = 0 0 1;
    func = file;
    time_file = "msf/m0090_z.txt";
    amplitude = 1.0;
};

source {
    coords = 10.50000 -7.00000 0.00000;
    type = impulse;
    dir = 1 0 0;
    func = file;
    time_file = "msf/m0091_x.txt";
    amplitude = 1.0;
};

source {
    coords = 10.50000 -7.00000 0.00000;
    type = impulse;
    dir = 0 1 0;
    func = file;
    time_file = "msf/m0091_y.txt";
    amplitude = 1.0;
};

source {
    coords = 10.50000 -7.00000 0.00000;
    type = impulse;
    dir = 0 0 1;
    func = file;
    time_file = "msf/m0091_z.txt";
    amplitude = 1.0;
};

source {
    coords = 10.50000 -3.50000 0.00000;
    type = impulse;
    dir = 1 0 0;
    func = file;
    time_file = "msf/m0092_x.txt";
    amplitude = 1.0;
};

source {
    coords = 10.50000 -3.50000 0.00000;
    type = impulse;
    dir = 0 1 0;
    func = file;
    time_file = "msf/m0092_y.txt";
    amplitude = 1.0;
};

source {
    coords = 10.50000 -3.50000 0.00000;
    type = impulse;
    dir = 0 0 1;
    func = file;
    time_file = "msf/m0092_z.txt";
    amplitude = 1.0;
};

source {
    coords = 10.50000 0.00000 0.00000;
    type = impulse;
    dir = 1 0 0;
    func = file;
    time_file = "msf/m0093_x.txt";
    amplitude = 1.0;
};

source {
    coords = 10.50000 0.00000 0.00000;
    type = impulse;
    dir = 0 1 0;
    func = file;
    time_file = "msf/m0093_y.txt";
    amplitude = 1.0;
};

source {
    coords = 10.50000 0.00000 0.00000;
    type = impulse;
    dir = 0 0 1;
    func = file;
    time_file = "msf/m0093_z.txt";
    amplitude = 1.0;
};

source {
    coords = 10.50000 3.50000 0.00000;
    type = impulse;
    dir = 1 0 0;
    func = file;
    time_file = "msf/m0094_x.txt";
    amplitude = 1.0;
};

source {
    coords = 10.50000 3.50000 0.00000;
    type = impulse;
    dir = 0 1 0;
    func = file;
    time_file = "msf/m0094_y.txt";
    amplitude = 1.0;
};

source {
    coords = 10.50000 3.50000 0.00000;
    type = impulse;
    dir = 0 0 1;
    func = file;
    time_file = "msf/m0094_z.txt";
    amplitude = 1.0;
};

source {
    coords = 10.50000 7.00000 0.00000;
    type = impulse;
    dir = 1 0 0;
    func = file;
    time_file = "msf/m0095_x.txt";
    amplitude = 1.0;
};

source {
    coords = 10.50000 7.00000 0.00000;
    type = impulse;
    dir = 0 1 0;
    func = file;
    time_file = "msf/m0095_y.txt";
    amplitude = 1.0;
};

source {
    coords = 10.50000 7.00000 0.00000;
    type = impulse;
    dir = 0 0 1;
    func = file;
    time_file = "msf/m0095_z.txt";
    amplitude = 1.0;
};

source {
    coords = 10.50000 10.50000 0.00000;
    type = impulse;
    dir = 1 0 0;
    func = file;
    time_file = "msf/m0096_x.txt";
    amplitude = 1.0;
};

source {
    coords = 10.50000 10.50000 0.00000;
    type = impulse;
    dir = 0 1 0;
    func = file;
    time_file = "msf/m0096_y.txt";
    amplitude = 1.0;
};

source {
    coords = 10.50000 10.50000 0.00000;
    type = impulse;
    dir = 0 0 1;
    func = file;
    time_file = "msf/m0096_z.txt";
    amplitude = 1.0;
};

source {
    coords = 10.50000 14.00000 0.00000;
    type = impulse;
    dir = 1 0 0;
    func = file;
    time_file = "msf/m0097_x.txt";
    amplitude = 1.0;
};

source {
    coords = 10.50000 14.00000 0.00000;
    type = impulse;
    dir = 0 1 0;
    func = file;
    time_file = "msf/m0097_y.txt";
    amplitude = 1.0;
};

source {
    coords = 10.50000 14.00000 0.00000;
    type = impulse;
    dir = 0 0 1;
    func = file;
    time_file = "msf/m0097_z.txt";
    amplitude = 1.0;
};

source {
    coords = 10.50000 17.50000 0.00000;
    type = impulse;
    dir = 1 0 0;
    func = file;
    time_file = "msf/m0098_x.txt";
    amplitude = 1.0;
};

source {
    coords = 10.50000 17.50000 0.00000;
    type = impulse;
    dir = 0 1 0;
    func = file;
    time_file = "msf/m0098_y.txt";
    amplitude = 1.0;
};

source {
    coords = 10.50000 17.50000 0.00000;
    type = impulse;
    dir = 0 0 1;
    func = file;
    time_file = "msf/m0098_z.txt";
    amplitude = 1.0;
};

source {
    coords = 14.00000 -17.50000 0.00000;
    type = impulse;
    dir = 1 0 0;
    func = file;
    time_file = "msf/m0099_x.txt";
    amplitude = 1.0;
};

source {
    coords = 14.00000 -17.50000 0.00000;
    type = impulse;
    dir = 0 1 0;
    func = file;
    time_file = "msf/m0099_y.txt";
    amplitude = 1.0;
};

source {
    coords = 14.00000 -17.50000 0.00000;
    type = impulse;
    dir = 0 0 1;
    func = file;
    time_file = "msf/m0099_z.txt";
    amplitude = 1.0;
};

source {
    coords = 14.00000 -14.00000 0.00000;
    type = impulse;
    dir = 1 0 0;
    func = file;
    time_file = "msf/m0100_x.txt";
    amplitude = 1.0;
};

source {
    coords = 14.00000 -14.00000 0.00000;
    type = impulse;
    dir = 0 1 0;
    func = file;
    time_file = "msf/m0100_y.txt";
    amplitude = 1.0;
};

source {
    coords = 14.00000 -14.00000 0.00000;
    type = impulse;
    dir = 0 0 1;
    func = file;
    time_file = "msf/m0100_z.txt";
    amplitude = 1.0;
};

source {
    coords = 14.00000 -10.50000 0.00000;
    type = impulse;
    dir = 1 0 0;
    func = file;
    time_file = "msf/m0101_x.txt";
    amplitude = 1.0;
};

source {
    coords = 14.00000 -10.50000 0.00000;
    type = impulse;
    dir = 0 1 0;
    func = file;
    time_file = "msf/m0101_y.txt";
    amplitude = 1.0;
};

source {
    coords = 14.00000 -10.50000 0.00000;
    type = impulse;
    dir = 0 0 1;
    func = file;
    time_file = "msf/m0101_z.txt";
    amplitude = 1.0;
};

source {
    coords = 14.00000 -7.00000 0.00000;
    type = impulse;
    dir = 1 0 0;
    func = file;
    time_file = "msf/m0102_x.txt";
    amplitude = 1.0;
};

source {
    coords = 14.00000 -7.00000 0.00000;
    type = impulse;
    dir = 0 1 0;
    func = file;
    time_file = "msf/m0102_y.txt";
    amplitude = 1.0;
};

source {
    coords = 14.00000 -7.00000 0.00000;
    type = impulse;
    dir = 0 0 1;
    func = file;
    time_file = "msf/m0102_z.txt";
    amplitude = 1.0;
};

source {
    coords = 14.00000 -3.50000 0.00000;
    type = impulse;
    dir = 1 0 0;
    func = file;
    time_file = "msf/m0103_x.txt";
    amplitude = 1.0;
};

source {
    coords = 14.00000 -3.50000 0.00000;
    type = impulse;
    dir = 0 1 0;
    func = file;
    time_file = "msf/m0103_y.txt";
    amplitude = 1.0;
};

source {
    coords = 14.00000 -3.50000 0.00000;
    type = impulse;
    dir = 0 0 1;
    func = file;
    time_file = "msf/m0103_z.txt";
    amplitude = 1.0;
};

source {
    coords = 14.00000 0.00000 0.00000;
    type = impulse;
    dir = 1 0 0;
    func = file;
    time_file = "msf/m0104_x.txt";
    amplitude = 1.0;
};

source {
    coords = 14.00000 0.00000 0.00000;
    type = impulse;
    dir = 0 1 0;
    func = file;
    time_file = "msf/m0104_y.txt";
    amplitude = 1.0;
};

source {
    coords = 14.00000 0.00000 0.00000;
    type = impulse;
    dir = 0 0 1;
    func = file;
    time_file = "msf/m0104_z.txt";
    amplitude = 1.0;
};

source {
    coords = 14.00000 3.50000 0.00000;
    type = impulse;
    dir = 1 0 0;
    func = file;
    time_file = "msf/m0105_x.txt";
    amplitude = 1.0;
};

source {
    coords = 14.00000 3.50000 0.00000;
    type = impulse;
    dir = 0 1 0;
    func = file;
    time_file = "msf/m0105_y.txt";
    amplitude = 1.0;
};

source {
    coords = 14.00000 3.50000 0.00000;
    type = impulse;
    dir = 0 0 1;
    func = file;
    time_file = "msf/m0105_z.txt";
    amplitude = 1.0;
};

source {
    coords = 14.00000 7.00000 0.00000;
    type = impulse;
    dir = 1 0 0;
    func = file;
    time_file = "msf/m0106_x.txt";
    amplitude = 1.0;
};

source {
    coords = 14.00000 7.00000 0.00000;
    type = impulse;
    dir = 0 1 0;
    func = file;
    time_file = "msf/m0106_y.txt";
    amplitude = 1.0;
};

source {
    coords = 14.00000 7.00000 0.00000;
    type = impulse;
    dir = 0 0 1;
    func = file;
    time_file = "msf/m0106_z.txt";
    amplitude = 1.0;
};

source {
    coords = 14.00000 10.50000 0.00000;
    type = impulse;
    dir = 1 0 0;
    func = file;
    time_file = "msf/m0107_x.txt";
    amplitude = 1.0;
};

source {
    coords = 14.00000 10.50000 0.00000;
    type = impulse;
    dir = 0 1 0;
    func = file;
    time_file = "msf/m0107_y.txt";
    amplitude = 1.0;
};

source {
    coords = 14.00000 10.50000 0.00000;
    type = impulse;
    dir = 0 0 1;
    func = file;
    time_file = "msf/m0107_z.txt";
    amplitude = 1.0;
};

source {
    coords = 14.00000 14.00000 0.00000;
    type = impulse;
    dir = 1 0 0;
    func = file;
    time_file = "msf/m0108_x.txt";
    amplitude = 1.0;
};

source {
    coords = 14.00000 14.00000 0.00000;
    type = impulse;
    dir = 0 1 0;
    func = file;
    time_file = "msf/m0108_y.txt";
    amplitude = 1.0;
};

source {
    coords = 14.00000 14.00000 0.00000;
    type = impulse;
    dir = 0 0 1;
    func = file;
    time_file = "msf/m0108_z.txt";
    amplitude = 1.0;
};

source {
    coords = 14.00000 17.50000 0.00000;
    type = impulse;
    dir = 1 0 0;
    func = file;
    time_file = "msf/m0109_x.txt";
    amplitude = 1.0;
};

source {
    coords = 14.00000 17.50000 0.00000;
    type = impulse;
    dir = 0 1 0;
    func = file;
    time_file = "msf/m0109_y.txt";
    amplitude = 1.0;
};

source {
    coords = 14.00000 17.50000 0.00000;
    type = impulse;
    dir = 0 0 1;
    func = file;
    time_file = "msf/m0109_z.txt";
    amplitude = 1.0;
};

source {
    coords = 17.50000 -17.50000 0.00000;
    type = impulse;
    dir = 1 0 0;
    func = file;
    time_file = "msf/m0110_x.txt";
    amplitude = 1.0;
};

source {
    coords = 17.50000 -17.50000 0.00000;
    type = impulse;
    dir = 0 1 0;
    func = file;
    time_file = "msf/m0110_y.txt";
    amplitude = 1.0;
};

source {
    coords = 17.50000 -17.50000 0.00000;
    type = impulse;
    dir = 0 0 1;
    func = file;
    time_file = "msf/m0110_z.txt";
    amplitude = 1.0;
};

source {
    coords = 17.50000 -14.00000 0.00000;
    type = impulse;
    dir = 1 0 0;
    func = file;
    time_file = "msf/m0111_x.txt";
    amplitude = 1.0;
};

source {
    coords = 17.50000 -14.00000 0.00000;
    type = impulse;
    dir = 0 1 0;
    func = file;
    time_file = "msf/m0111_y.txt";
    amplitude = 1.0;
};

source {
    coords = 17.50000 -14.00000 0.00000;
    type = impulse;
    dir = 0 0 1;
    func = file;
    time_file = "msf/m0111_z.txt";
    amplitude = 1.0;
};

source {
    coords = 17.50000 -10.50000 0.00000;
    type = impulse;
    dir = 1 0 0;
    func = file;
    time_file = "msf/m0112_x.txt";
    amplitude = 1.0;
};

source {
    coords = 17.50000 -10.50000 0.00000;
    type = impulse;
    dir = 0 1 0;
    func = file;
    time_file = "msf/m0112_y.txt";
    amplitude = 1.0;
};

source {
    coords = 17.50000 -10.50000 0.00000;
    type = impulse;
    dir = 0 0 1;
    func = file;
    time_file = "msf/m0112_z.txt";
    amplitude = 1.0;
};

source {
    coords = 17.50000 -7.00000 0.00000;
    type = impulse;
    dir = 1 0 0;
    func = file;
    time_file = "msf/m0113_x.txt";
    amplitude = 1.0;
};

source {
    coords = 17.50000 -7.00000 0.00000;
    type = impulse;
    dir = 0 1 0;
    func = file;
    time_file = "msf/m0113_y.txt";
    amplitude = 1.0;
};

source {
    coords = 17.50000 -7.00000 0.00000;
    type = impulse;
    dir = 0 0 1;
    func = file;
    time_file = "msf/m0113_z.txt";
    amplitude = 1.0;
};

source {
    coords = 17.50000 -3.50000 0.00000;
    type = impulse;
    dir = 1 0 0;
    func = file;
    time_file = "msf/m0114_x.txt";
    amplitude = 1.0;
};

source {
    coords = 17.50000 -3.50000 0.00000;
    type = impulse;
    dir = 0 1 0;
    func = file;
    time_file = "msf/m0114_y.txt";
    amplitude = 1.0;
};

source {
    coords = 17.50000 -3.50000 0.00000;
    type = impulse;
    dir = 0 0 1;
    func = file;
    time_file = "msf/m0114_z.txt";
    amplitude = 1.0;
};

source {
    coords = 17.50000 0.00000 0.00000;
    type = impulse;
    dir = 1 0 0;
    func = file;
    time_file = "msf/m0115_x.txt";
    amplitude = 1.0;
};

source {
    coords = 17.50000 0.00000 0.00000;
    type = impulse;
    dir = 0 1 0;
    func = file;
    time_file = "msf/m0115_y.txt";
    amplitude = 1.0;
};

source {
    coords = 17.50000 0.00000 0.00000;
    type = impulse;
    dir = 0 0 1;
    func = file;
    time_file = "msf/m0115_z.txt";
    amplitude = 1.0;
};

source {
    coords = 17.50000 3.50000 0.00000;
    type = impulse;
    dir = 1 0 0;
    func = file;
    time_file = "msf/m0116_x.txt";
    amplitude = 1.0;
};

source {
    coords = 17.50000 3.50000 0.00000;
    type = impulse;
    dir = 0 1 0;
    func = file;
    time_file = "msf/m0116_y.txt";
    amplitude = 1.0;
};

source {
    coords = 17.50000 3.50000 0.00000;
    type = impulse;
    dir = 0 0 1;
    func = file;
    time_file = "msf/m0116_z.txt";
    amplitude = 1.0;
};

source {
    coords = 17.50000 7.00000 0.00000;
    type = impulse;
    dir = 1 0 0;
    func = file;
    time_file = "msf/m0117_x.txt";
    amplitude = 1.0;
};

source {
    coords = 17.50000 7.00000 0.00000;
    type = impulse;
    dir = 0 1 0;
    func = file;
    time_file = "msf/m0117_y.txt";
    amplitude = 1.0;
};

source {
    coords = 17.50000 7.00000 0.00000;
    type = impulse;
    dir = 0 0 1;
    func = file;
    time_file = "msf/m0117_z.txt";
    amplitude = 1.0;
};

source {
    coords = 17.50000 10.50000 0.00000;
    type = impulse;
    dir = 1 0 0;
    func = file;
    time_file = "msf/m0118_x.txt";
    amplitude = 1.0;
};

source {
    coords = 17.50000 10.50000 0.00000;
    type = impulse;
    dir = 0 1 0;
    func = file;
    time_file = "msf/m0118_y.txt";
    amplitude = 1.0;
};

source {
    coords = 17.50000 10.50000 0.00000;
    type = impulse;
    dir = 0 0 1;
    func = file;
    time_file = "msf/m0118_z.txt";
    amplitude = 1.0;
};

source {
    coords = 17.50000 14.00000 0.00000;
    type = impulse;
    dir = 1 0 0;
    func = file;
    time_file = "msf/m0119_x.txt";
    amplitude = 1.0;
};

source {
    coords = 17.50000 14.00000 0.00000;
    type = impulse;
    dir = 0 1 0;
    func = file;
    time_file = "msf/m0119_y.txt";
    amplitude = 1.0;
};

source {
    coords = 17.50000 14.00000 0.00000;
    type = impulse;
    dir = 0 0 1;
    func = file;
    time_file = "msf/m0119_z.txt";
    amplitude = 1.0;
};

source {
    coords = 17.50000 17.50000 0.00000;
    type = impulse;
    dir = 1 0 0;
    func = file;
    time_file = "msf/m0120_x.txt";
    amplitude = 1.0;
};

source {
    coords = 17.50000 17.50000 0.00000;
    type = impulse;
    dir = 0 1 0;
    func = file;
    time_file = "msf/m0120_y.txt";
    amplitude = 1.0;
};

source {
    coords = 17.50000 17.50000 0.00000;
    type = impulse;
    dir = 0 0 1;
    func = file;
    time_file = "msf/m0120_z.txt";
    amplitude = 1.0;
};

time_scheme {
    accel_scheme = false;
    veloc_scheme = true;
    alpha = 0.5;
    beta = 0.5;
    gamma = 1;
    courant = 0.2;
};

pml_infos {
    pml_type = CPML;
    cpml_kappa0 = 10.0;
    cpml_kappa1 = 10.0;
    cpml_rc = 0.000000001;
    cpml_integration = Order2;
};

out_variables {
    enP  = 0;
    enS  = 0;
    evol = 1;  # volumetric strain
    pre  = 0;
    dis  = 1;  # displacement
    vel  = 0;
    acc  = 0;
    edev = 1;  # deviatoric strain
    sdev = 0;
};
